Hw02 unpack string
gerladeno/otus-homeworks pull request #3
Opened 2020-12-07 13:31 UTC by gerladeno

## Домашнее задание №2 «Распаковка строки»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-12-10 11:35 UTC, kulti requested changes
В решение есть одна ошибка — строку нужно обходить по рунам, а не по байтам. Остальное — косметика и оптимизации.

Предлагаю поправить ошибку — будет принято на 7/10. Если хочется 10, то надо улучшать код.

2020-12-10 11:35 UTC, kulti commented on hw02_unpack_string/unpack.go
> +	for i, v := range p.bytes {
Строки в Go — это набор UTF-8 символов. Строки состоят из rune, а не байт. Обход строки побайтово будет неккоретно работать с любым не ASCII символом (например, с кириллицей).

2020-12-10 11:35 UTC, kulti commented on hw02_unpack_string/unpack.go
> +	tmp := make([]byte, 0)
Посмотрите на strings.Builder. Он тоже использует слайс, но там уже есть все необходимые методы для оптимальной записи разных типов (строк, байт, рун).

2020-12-10 11:35 UTC, kulti commented on hw02_unpack_string/unpack.go
> +		}
В этом свитче намешаны разнотипные условия. Довольно сложная и неочевидная конструкция получилась. Первый вопрос к таким навороченным свитчам (и if'aм) — тут точно все случае учтены? Понимать и поддерживать подобный код будет очень больно.

2020-12-10 11:35 UTC, kulti commented on hw02_unpack_string/unpack.go
> +	if err := str.isValid(); err != nil {
Интересное решение, но неоптимальное. Получается двойной обход строки.

Можно все сделать за один цикл.

2020-12-10 11:35 UTC, kulti commented on hw02_unpack_string/unpack_test.go
> +		t.Run(tc.input, func(t *testing.T) {
Да, так тесты намного понятнее и аккуратнее выглядят. Не хватает только `tc := tc` перед `t.Run`.

2020-12-10 21:25 UTC, gerladeno commented on hw02_unpack_string/unpack.go
> +	for i, v := range p.bytes {
Поправил

2020-12-10 21:25 UTC, gerladeno commented on hw02_unpack_string/unpack.go
> +		}
Не знаю, можно ли сказать, что поправил, но изменил :)

2020-12-10 21:25 UTC, gerladeno commented on hw02_unpack_string/unpack.go
> +	if err := str.isValid(); err != nil {
Делаю за 1

2020-12-10 21:26 UTC, gerladeno commented on hw02_unpack_string/unpack_test.go
> +		t.Run(tc.input, func(t *testing.T) {
Исправил

2020-12-10 21:26 UTC, gerladeno commented on hw02_unpack_string/unpack.go
> +	tmp := make([]byte, 0)
Переделал

2020-12-10 21:28 UTC, gerladeno commented
Всё исправил, * не сделал

2020-12-12 09:25 UTC, kulti commented on hw02_unpack_string/unpack.go
> +	for i, v := range p.bytes {
Помимо прочего это был намек на то, что неплохо бы добавить тест на работу с не ASCII символом :)

2020-12-12 09:49 UTC, kulti submitted a review, later dismissed
Вроде алгоритм рабочий, хоть и сложноватый. Новые тесты есть, код немного запутанный и не очень чистый. ДЗ принято — 7/10.

2020-12-12 09:49 UTC, kulti commented on hw02_unpack_string/unpack.go
> +	case '\\':
Вроде, вы написали, что не делали решение со звездочкой? И в тестах t.Skip() остался.

Тогда зачем здесь обработка экранирующего слэша?

2020-12-12 09:49 UTC, kulti commented on hw02_unpack_string/unpack.go
> +	result := new(strings.Builder)
В go очень редко используют new. Чаще будет вариант `result := &strings.Builder{}`.

new полезен для создания указателя на число с конкретным значением за одну операцию — `pi := new(3)`. Довольно редкая ситуация.

2020-12-12 09:49 UTC, kulti commented on hw02_unpack_string/unpack.go
> +	runes := []rune(s)
На всякий случай скажу, что тут будет аллокация под слайс рун и копирование содержимого строки в него. Т.е. это все еще не самый оптимальный вариант.

Строку можно обойти по-рунно используя такой цикл `for _, r := range s`. Т.к. ваш алгоритм заточен на счетчик цикла, то вам этот вариант не подойдет. Возьмите на заметку, на будущее :)

2020-12-12 09:49 UTC, kulti commented on hw02_unpack_string/unpack.go
> +	case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
`case unicode.IsDigit(*first):`

2020-12-12 09:49 UTC, kulti commented on hw02_unpack_string/unpack.go
> +			i, _ := strconv.Atoi(string(*second))
Игнорировать ошибку, даже если она кажется невозможной, так себе затея. Кто-то изменит код из-за которого тут делается такое предположение и приплыли.

Можно еще вот так сконвертировать `i := *second - '0'`. Без аллокаций под строку и вызова сложного алгоритма.

2020-12-12 09:49 UTC, kulti commented on hw02_unpack_string/unpack.go
> +	}
Алгоритм все еще сложный и запутанный. Дело в том, что управление счетчиком идет и внутри цикла и в самом цикле. Из-за этого довольно странные условия приходится писать. Какой-то артефакт работы  processTwoRunes в виде флага. Анализировать и поддерживать такой код будет сложно.

Тем не менее, вроде, все должно работать (только case c \ не смотрел, т.к. вы написали, что не делали его).

Если захотите сделать хороший понятный код, то предлагаю подумать в другом направлении.
1. Обходить строку по-рунно (через цикл for range).
2. Принимать решение, исходя из текущей руны и некоторого сохраненного состояния.

Получится простая и понятная стейт-машина.

2020-12-13 15:13 UTC, gerladeno commented
Переделал

2020-12-18 16:58 UTC, kulti approved these changes
Теперь логика решения хорошо структурирована. Круто, что заодно сделали и задание со звездочкой 👍 

Поднял баллы до 10.

2020-12-18 17:36 UTC, merged